services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      - LOG_LEVEL=info

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: service
    environment:
      - LOG_LEVEL=debug
