services:
  api-gateway:
    build:
      context: ./api_gateway  # executes commands from this directory
      dockerfile: Dockerfile
    container_name: api_gateway

  service:
    build:
      context: ./service  # executes commands from this directory
      dockerfile: Dockerfile
    container_name: service
