services:
  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: api_gateway

  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    container_name: service