name: Build and Push Docker Images

on:
  push:
    branches: [ dev ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: marco.fontana17/cce_prototipo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Images

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Module 1
        id: meta1
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch,suffix=-module1
            type=sha,prefix=dev-,suffix=-module1
            type=raw,value=module1-latest,enable={{is_default_branch}}

      - name: Extract metadata for Module 2
        id: meta2
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch,suffix=-module2
            type=sha,prefix=dev-,suffix=-module2
            type=raw,value=module2-latest,enable={{is_default_branch}}

      - name: Build and push Module 1
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./module1/Dockerfile
          push: true
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Module 2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./module2/Dockerfile
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max